# Newport

[TRA12CC]
controllers = ["CONEXCC"]
pos_unit = "mm"
min_pos = 0.0
max_pos = 12.0
resolution = 0.0002

[AG-M100D]
controllers = ["CONEXAGAP"]
pos_unit = "deg"
min_pos = -0.75
max_pos = 0.75
resolution = 0.001
